# Generated by Django 3.2 on 2022-02-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_crated',
            new_name='date_created',
        ),
    ]
